# -*- coding: utf-8 -*-
"""MSIS 522 Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCPO6nW_k8ZlTwhR6oFyNN0nOTwv64cp
"""

# Shin Tran
# MSIS 522
# Due March 8, 2026

# Individual Assignment 1
# NFL Analysis - Predicting Wins

import pandas as pd
import numpy as np

#Importing and merging the datase, display the statistica for the win percentage column
df_off0 = pd.read_csv('yearly_team_stats_offense.csv')
df_def0 = pd.read_csv('yearly_team_stats_defense.csv')

df_off1 = df_off0[df_off0['season_type'] == 'REG']
df_def1 = df_def0[df_def0['season_type'] == 'REG']

df_combined = df_off1.merge(df_def1, on = ['team', 'season'],
                            how = 'left', suffixes = ('_offense', '_defense'))
df_combined = df_combined.rename(columns={'win_pct_offense': 'win_pct'})
df_combined = df_combined.drop(columns=['win_pct_defense'])

print("\nDescriptive statistics for 'win_pct' column:")
print(df_combined['win_pct'].describe())

# Extract the numerical columns from the dataset
numerical_cols = df_combined.select_dtypes(include=np.number).columns

# Calculate Pearson correlation coefficients with 'win_pct'
correlations = df_combined[numerical_cols].corr()['win_pct']

# Drop the 'win_pct' correlation with itself and other highly correlated 'win' columns
correlations = correlations.drop(['win_pct', 'win_offense', 'win_defense'])

# Sort correlations in descending order
sorted_correlations = correlations.sort_values(ascending=False)

print("Top positive correlations with 'win_pct':")
print(sorted_correlations[sorted_correlations >= 0.4])

# Create a new dataframe with the top positive correlations, removed the
# redundant rows
df_combined1 = df_combined [['team','season','total_off_points','total_tds',
                             'td_pct','pass_pct_defense','rec_td_pct',
                             'receiving_touchdown','total_off_yards','ypa',
                             'win_pct']]

df_combined1

"""Target Distribution"""

import matplotlib.pyplot as plt
import seaborn as sns

# Plots the distirbution of the win percentage, and show the KDE line
plt.figure(figsize=(10, 6))
sns.histplot(df_combined1['win_pct'], bins=20, kde=True)
plt.title('Distribution of Win Percentage')
plt.xlabel('Win Percentage')
plt.ylabel('Frequency')
plt.grid(True, linestyle='-', alpha=0.7)
plt.show()

"""Feature Distributions and Relationships"""

plt.figure(figsize=(10, 6))
sns.regplot(x='total_off_points', y='win_pct', data=df_combined1,
            scatter_kws={'alpha':0.6}, line_kws={'color':'red'})
plt.title('Total Offensive Points vs. Win Percentage with Regression Line')
plt.xlabel('Total Offensive Points')
plt.ylabel('Win Percentage')
plt.grid(True, linestyle='-', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='season', y='win_pct', data=df_combined1)
plt.title('Win Percentage Distribution Across Seasons')
plt.xlabel('Season')
plt.ylabel('Win Percentage')
plt.xticks(rotation=45) # Rotate x-axis labels for better readability
plt.grid(axis='y', linestyle='-', alpha=0.7)
plt.show()

columns_for_pairplot = ['total_off_points', 'td_pct', 'pass_pct_defense', 'win_pct']
sns.pairplot(df_combined1[columns_for_pairplot])
plt.suptitle('Pair Plot of Key Offensive/Defensive Metrics and Win Percentage', y=1.02)
plt.show()

avg_win_pct_by_team = df_combined1.groupby('team')['win_pct'].mean().sort_values(ascending=False)

top_5_teams = avg_win_pct_by_team.head(5)
bottom_5_teams = avg_win_pct_by_team.tail(5)

print("Top 5 Teams by Average Win Percentage:\n", top_5_teams)
print("\nBottom 5 Teams by Average Win Percentage:\n", bottom_5_teams)

combined_teams = pd.concat([top_5_teams, bottom_5_teams])

plt.figure(figsize=(10, 6))
sns.barplot(x=combined_teams.index, y=combined_teams.values, hue=combined_teams.index, palette='viridis', legend=False)
plt.title('Average Win Percentage: Top 5 vs. Bottom 5 Teams')
plt.xlabel('Team')
plt.ylabel('Average Win Percentage')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='-', alpha=0.7)
plt.show()

avg_off_points_by_season = df_combined1.groupby('season')['total_off_points'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.lineplot(x='season', y='total_off_points', data=avg_off_points_by_season, marker='o')
plt.title('Average Total Offensive Points by Season')
plt.xlabel('Season')
plt.ylabel('Average Total Offensive Points')
plt.grid(True, linestyle='-', alpha=0.7)
plt.xticks(rotation=45)
plt.show()

"""Correlation Heatmap"""

import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the correlation matrix for the numerical columns
correlation_matrix = df_combined1.drop(columns=['team', 'season'])
correlation_matrix = correlation_matrix.select_dtypes(include=np.number).corr()

# Plot the heatmap
plt.figure(figsize=(8, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Key Features and Win Percentage')
plt.show()

"""Data Preparation"""

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df_combined1.drop(columns=['team', 'season', 'win_pct'])
y = df_combined1['win_pct']

# Perform the train-test split (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""Linear Regression Baseline"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Initialize the Linear Regression model
linear_model = LinearRegression()

# Train the model using the training data
linear_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = linear_model.predict(X_test)

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("--- Linear Regression Baseline Model ---")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R-squared (R²): {r2:.4f}")

"""Lasso, Ridge, and Elastic-Net cariants"""

from sklearn.linear_model import Lasso, Ridge, ElasticNet
from sklearn.model_selection import GridSearchCV

# --- 1. Lasso Regression ---

# Define the parameter grid for Lasso
lasso_params = {'alpha': np.logspace(-4, 0, 20)} # Explore alpha from 0.0001 to 1

# Initialize Lasso model
lasso = Lasso(random_state=42, max_iter=2000)

# Perform GridSearchCV
grid_search_lasso = GridSearchCV(lasso, lasso_params, cv=5,
                                 scoring='neg_mean_squared_error', n_jobs=-1)
grid_search_lasso.fit(X_train, y_train)

# Get the best Lasso model
best_lasso = grid_search_lasso.best_estimator_

# Make predictions and evaluate
y_pred_lasso = best_lasso.predict(X_test)
mae_lasso = mean_absolute_error(y_test, y_pred_lasso)
mse_lasso = mean_squared_error(y_test, y_pred_lasso)
rmse_lasso = np.sqrt(mse_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print("--- Tuned Lasso Regression ---")
print(f"Best Alpha: {grid_search_lasso.best_params_['alpha']:.4f}")
print(f"Mean Absolute Error (MAE): {mae_lasso:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_lasso:.4f}")
print(f"R-squared (R²): {r2_lasso:.4f}")

# --- 2. Ridge Regression ---

# Define the parameter grid for Ridge
# Explore alpha from 0.0001 to 100
ridge_params = {'alpha': np.logspace(-4, 2, 20)}

# Initialize Ridge model
ridge = Ridge(random_state=42, max_iter=2000)

# Perform GridSearchCV
grid_search_ridge = GridSearchCV(ridge, ridge_params, cv=5,
                                 scoring='neg_mean_squared_error', n_jobs=-1)
grid_search_ridge.fit(X_train, y_train)

# Get the best Ridge model
best_ridge = grid_search_ridge.best_estimator_

# Make predictions and evaluate
y_pred_ridge = best_ridge.predict(X_test)
mae_ridge = mean_absolute_error(y_test, y_pred_ridge)
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
rmse_ridge = np.sqrt(mse_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print("\n--- Tuned Ridge Regression ---")
print(f"Best Alpha: {grid_search_ridge.best_params_['alpha']:.4f}")
print(f"Mean Absolute Error (MAE): {mae_ridge:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_ridge:.4f}")
print(f"R-squared (R²): {r2_ridge:.4f}")

# --- 3. Elastic-Net Regression ---

# Define the parameter grid for Elastic-Net
elastic_net_params = {
    'alpha': np.logspace(-4, 0, 10),
    'l1_ratio': np.arange(0.1, 1.0, 0.2) # Explore l1_ratio from 0.1 to 0.9
}

# Initialize Elastic-Net model
elastic_net = ElasticNet(random_state=42, max_iter=2000)

# Perform GridSearchCV
grid_search_elastic_net = GridSearchCV(elastic_net, elastic_net_params, cv=5,
                                       scoring='neg_mean_squared_error', n_jobs=-1)
grid_search_elastic_net.fit(X_train, y_train)

# Get the best Elastic-Net model
best_elastic_net = grid_search_elastic_net.best_estimator_

# Make predictions and evaluate
y_pred_elastic_net = best_elastic_net.predict(X_test)
mae_elastic_net = mean_absolute_error(y_test, y_pred_elastic_net)
mse_elastic_net = mean_squared_error(y_test, y_pred_elastic_net)
rmse_elastic_net = np.sqrt(mse_elastic_net)
r2_elastic_net = r2_score(y_test, y_pred_elastic_net)

print("\n--- Tuned Elastic-Net Regression ---")
print(f"Best Alpha: {grid_search_elastic_net.best_params_['alpha']:.4f}")
print(f"Best L1 Ratio: {grid_search_elastic_net.best_params_['l1_ratio']:.2f}")
print(f"Mean Absolute Error (MAE): {mae_elastic_net:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_elastic_net:.4f}")
print(f"R-squared (R²): {r2_elastic_net:.4f}")

"""Decision Tree/CART"""

from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.model_selection import GridSearchCV

# --- 1. Define the Decision Tree Regressor model ---
dt = DecisionTreeRegressor(random_state=42)

# --- 2. Define the hyperparameter grid for GridSearchCV ---
param_grid = {
    'max_depth': [3, 5, 7, 10, None], # None means unlimited depth
    'min_samples_leaf': [5, 10, 20, 50]
}

# --- 3. Implement 5-fold cross-validation with GridSearchCV ---
grid_search_dt = GridSearchCV(
    estimator=dt,
    param_grid=param_grid,
    cv=5, # 5-fold cross-validation
    scoring='neg_mean_squared_error', # Appropriate scoring for regression
    n_jobs=-1, # Use all available cores
    verbose=1
)

grid_search_dt.fit(X_train, y_train)

# --- 4. Report and save the best hyperparameters ---
best_dt = grid_search_dt.best_estimator_
best_params = grid_search_dt.best_params_

print("--- Tuned Decision Tree Regressor ---")
print(f"Best Hyperparameters: {best_params}")

# --- 5. Evaluate the best model on the test set ---
y_pred_dt = best_dt.predict(X_test)
mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
rmse_dt = np.sqrt(mse_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print(f"Mean Absolute Error (MAE): {mae_dt:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_dt:.4f}")
print(f"R-squared (R²): {r2_dt:.4f}")

# --- 6. Visualize the best tree (if not too deep) ---
# Set a reasonable limit for visualization depth
max_plot_depth = 5

if best_params['max_depth'] is not None and best_params['max_depth'] <= max_plot_depth:
    plt.figure(figsize=(12, 6))
    plot_tree(best_dt, feature_names=X_train.columns, filled=True, rounded=True, fontsize=8)
    plt.title(f"Best Decision Tree Regressor (Max Depth: {best_params['max_depth']}, Min Samples Leaf: {best_params['min_samples_leaf']})")
    plt.show()
elif best_params['max_depth'] is None or best_params['max_depth'] > max_plot_depth:
    print(f"\nSkipping tree visualization: max_depth ({best_params['max_depth'] if best_params['max_depth'] is not None else 'None'}) is too deep for clear display.")

"""Random Forest"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

# --- 1. Define the Random Forest Regressor model ---
rf = RandomForestRegressor(random_state=42)

# --- 2. Define the hyperparameter grid for GridSearchCV ---
param_grid_rf = {
    'n_estimators': [50, 100, 200], # Number of trees in the forest
    'max_depth': [3, 5, 8, None] # Maximum depth of the tree
}

# --- 3. Implement 5-fold cross-validation with GridSearchCV ---
grid_search_rf = GridSearchCV(
    estimator=rf,
    param_grid=param_grid_rf,
    cv=5, # 5-fold cross-validation
    scoring='neg_mean_squared_error', # Appropriate scoring for regression
    n_jobs=-1, # Use all available cores
    verbose=1
)

grid_search_rf.fit(X_train, y_train)

# --- 4. Report and save the best hyperparameters ---
best_rf = grid_search_rf.best_estimator_
best_params_rf = grid_search_rf.best_params_

print("--- Tuned Random Forest Regressor ---")
print(f"Best Hyperparameters: {best_params_rf}")

# --- 5. Evaluate the best model on the test set ---
y_pred_rf = best_rf.predict(X_test)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"Mean Absolute Error (MAE): {mae_rf:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_rf:.4f}")
print(f"R-squared (R²): {r2_rf:.4f}")

# --- 6. Plot predicted vs. actual values ---
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred_rf, alpha=0.6)
# Diagonal line for perfect prediction
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Actual Win Percentage')
plt.ylabel('Predicted Win Percentage')
plt.title('Random Forest Regressor: Predicted vs. Actual Win Percentage')
plt.grid(True)
plt.show()

"""Boosted Trees - LightGBM"""

from lightgbm import LGBMRegressor
from sklearn.model_selection import GridSearchCV

# --- 1. Define the LightGBM Regressor model ---
# verbose=-1 to suppress warnings during tuning
lgbm = LGBMRegressor(random_state=42, verbose=-1)

# --- 2. Define the hyperparameter grid for GridSearchCV ---
param_grid_lgbm = {
    'n_estimators': [50, 100, 200], # Number of boosting rounds
    'max_depth': [3, 4, 5, 6],     # Maximum tree depth
    'learning_rate': [0.01, 0.05, 0.1] # Step size shrinkage to prevent overfitting
}

# --- 3. Implement 5-fold cross-validation with GridSearchCV ---
grid_search_lgbm = GridSearchCV(
    estimator=lgbm,
    param_grid=param_grid_lgbm,
    cv=5, # 5-fold cross-validation
    scoring='neg_mean_squared_error', # Appropriate scoring for regression
    n_jobs=-1, # Use all available cores
    verbose=1
)

grid_search_lgbm.fit(X_train, y_train)

# --- 4. Report and save the best hyperparameters ---
best_lgbm = grid_search_lgbm.best_estimator_
best_params_lgbm = grid_search_lgbm.best_params_

print("--- Tuned LightGBM Regressor ---")
print(f"Best Hyperparameters: {best_params_lgbm}")

# --- 5. Evaluate the best model on the test set ---
y_pred_lgbm = best_lgbm.predict(X_test)
mae_lgbm = mean_absolute_error(y_test, y_pred_lgbm)
mse_lgbm = mean_squared_error(y_test, y_pred_lgbm)
rmse_lgbm = np.sqrt(mse_lgbm)
r2_lgbm = r2_score(y_test, y_pred_lgbm)

print(f"Mean Absolute Error (MAE): {mae_lgbm:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_lgbm:.4f}")
print(f"R-squared (R²): {r2_lgbm:.4f}")

# --- 6. Plot predicted vs. actual values ---
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred_lgbm, alpha=0.6)
# Diagonal line for perfect prediction
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Actual Win Percentage')
plt.ylabel('Predicted Win Percentage')
plt.title('LightGBM Regressor: Predicted vs. Actual Win Percentage')
plt.grid(True)
plt.show()

"""Neural Network - MLP"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from sklearn.preprocessing import StandardScaler # Import StandardScaler

# --- 1. Scale the data ---
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# --- 2. Build the MLP model ---
# Define the input shape based on the training data's feature dimensions
input_shape = X_train_scaled.shape[1] # Use scaled data shape

model = keras.Sequential([
    layers.Input(shape=(input_shape,)),
    layers.Dense(128, activation='relu', name='hidden_layer_1'),
    layers.Dense(128, activation='relu', name='hidden_layer_2'),
    layers.Dense(1, activation='linear', name='output_layer') # Linear activation for regression
])

# --- 3. Compile the model ---
model.compile(
    optimizer='adam',
    loss='mean_squared_error', # Appropriate loss function for regression
    metrics=['mae'] # Mean Absolute Error as an additional metric during training
)

model.summary()

# --- 4. Train the model ---
print("\n--- Training the MLP Model ---")
history = model.fit(
    X_train_scaled, # Use scaled training data
    y_train,
    epochs=100, # Number of epochs to train for
    batch_size=32, # Number of samples per gradient update
    validation_split=0.2, # Use 20% of training data for validation
    verbose=0 # Suppress verbose output during training
)

print("MLP Model Training Complete.")

# --- 5. Plot the training history ---
# Plot training & validation loss values
plt.figure(figsize=(10, 6))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss History')
plt.ylabel('Loss (MSE)')
plt.xlabel('Epoch')
plt.legend(loc='upper right')
plt.grid(True)
plt.show()

# Plot training & validation MAE values
plt.figure(figsize=(10, 6))
plt.plot(history.history['mae'], label='Train MAE')
plt.plot(history.history['val_mae'], label='Validation MAE')
plt.title('Model MAE History')
plt.ylabel('MAE')
plt.xlabel('Epoch')
plt.legend(loc='upper right')
plt.grid(True)
plt.show()

# --- 6. Report test-set metrics ---
print("\n--- Evaluating MLP Model on Test Set ---")
y_pred_mlp = model.predict(X_test_scaled).flatten() # Use scaled test data

mae_mlp = mean_absolute_error(y_test, y_pred_mlp)
mse_mlp = mean_squared_error(y_test, y_pred_mlp)
rmse_mlp = np.sqrt(mse_mlp)
r2_mlp = r2_score(y_test, y_pred_mlp)

print(f"Mean Absolute Error (MAE): {mae_mlp:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse_mlp:.4f}")
print(f"R-squared (R²): {r2_mlp:.4f}")

"""Model Summary Comparison

| Model                        | MAE    | RMSE   | R²     |
| :--------------------------- | :----- | :----- | :----- |
| Linear Regression            | 0.0847 | 0.1029 | 0.6581 |
| Tuned Lasso Regression       | 0.0843 | 0.1027 | 0.6595 |
| Tuned Ridge Regression       | 0.0846 | 0.1029 | 0.6583 |
| Tuned Elastic-Net Regression | 0.0844 | 0.1029 | 0.6583 |
| Tuned Decision Tree          | 0.1004 | 0.1239 | 0.5039 |
| Tuned Random Forest          | 0.0924 | 0.1132 | 0.5858 |
| Tuned LightGBM Regressor     | 0.0935 | 0.1147 | 0.5752 |
| MLP (Scaled Features)        | 0.1082 | 0.1302 | 0.4527 |
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data for plotting (RMSE values from previous runs)
model_performance = {
    'Model': [
        'Linear Regression',
        'Tuned Lasso Regression',
        'Tuned Ridge Regression',
        'Tuned Elastic-Net Regression',
        'Tuned Decision Tree',
        'Tuned Random Forest',
        'Tuned LightGBM Regressor',
        'MLP (Scaled Features)'
    ],
    'RMSE': [
        0.1029,
        0.1027,
        0.1029,
        0.1029,
        0.1239,
        0.1132,
        0.1147,
        0.1302
    ]
}

df_performance = pd.DataFrame(model_performance)

# Sort by RMSE for better visualization
df_performance = df_performance.sort_values(by='RMSE', ascending=True)

plt.figure(figsize=(10, 6))
sns.barplot(x='RMSE', y='Model', data=df_performance, hue='Model', palette='viridis', legend=False)
plt.title('Comparison of Model RMSE on Test Set')
plt.xlabel('Root Mean Squared Error (RMSE)')
plt.ylabel('Model')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.xlim(0.09, 0.14) # Set x-axis limits to focus on the relevant range
plt.tight_layout()
plt.show()

"""Among all the models tested, the Tuned Lasso Regression performed the best, achieving the lowest Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE), and the highest R-squared (R²) value. It was closely followed by the other linear models (Linear Regression, Tuned Ridge Regression, and Tuned Elastic-Net Regression). The ensemble methods (Random Forest and LightGBM) showed improved performance over the single Decision Tree but did not surpass the linear models. The Multi-Layer Perceptron (MLP), despite significant improvement after feature scaling, still lagged behind the other models.

I was actually not surprised by the simpler linear models outperforming the more complex models on this dataset. Usually, gradient-boosting machines like LightGBM or more extensively tuned neural networks are expected to achieve better results. This suggests that the relationship between the strongly correlated metrics and NFL win percentage is predominantly linear. The additional complexity of the other models either didn't find much more signal or overfit slightly. Although it was expected given that the Pearson correlation coefficient was used to narrow the dataset down to several columns with a coefficient above 0.5 when compared to the win percentage.


Several trade-offs exist between these models:

*   Accuracy vs. Interpretability: Linear models (Linear Regression, Lasso, Ridge, Elastic-Net) offer excellent interpretability, as the coefficients directly show the impact of each feature on the target. Lasso further aids interpretability through feature selection. In contrast, ensemble methods (Random Forest, LightGBM) and particularly the MLP are often considered "black boxes," providing high accuracy but limited insight into how they arrive at their predictions.
*   Training Time & Complexity: Linear models are generally very fast to train due to their simpler mathematical foundations. Tree-based ensembles require more training time as they build multiple trees, though LightGBM is optimized for speed. Neural networks (MLPs) can be computationally intensive, requiring more epochs and potentially specialized hardware, and are also sensitive to data scaling.
*   Overfitting Risk: Regularized linear models (Lasso, Ridge, Elastic-Net) explicitly tackle overfitting by penalizing large coefficients. Ensemble methods are inherently robust to overfitting due to their averaging and boosting techniques. A single Decision Tree is prone to overfitting if not carefully constrained (e.g., max_depth). MLPs can also overfit if too complex or not properly regularized.

SHAP Analysis
"""

import shap
import matplotlib.pyplot as plt

# Assuming best_rf is the best-performing Random Forest Regressor from previous steps
# and X_test is your test feature set.

# 1. Use the new Explainer API (more robust than TreeExplainer for plots)
explainer = shap.Explainer(best_rf, X_test)
shap_values_obj = explainer(X_test)

# 2. Clear previous figure states
plt.close('all')

# 3. Use the dedicated beeswarm plot function
# This uses the Explanation object which carries its own feature names and data
shap.plots.beeswarm(shap_values_obj, show=False)

# 4. Final formatting
plt.title('SHAP Summary Plot (Beeswarm) for Random Forest Regressor', pad=20)
fig = plt.gcf()
fig.set_size_inches(10, 6)
plt.show()

# --- Required Plot 2: Bar plot of mean absolute SHAP values ---
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_values_obj, X_test, plot_type='bar', show=False,
                  feature_names=X_test.columns.tolist())
plt.title('Feature Importance (Mean Absolute SHAP Value) for Random Forest Regressor')
plt.tight_layout()
plt.show()
plt.close() # Close the figure to prevent interference with subsequent plots

# --- Required Plot 3: Waterfall plot for one specific prediction ---
# Choose an interesting instance from the test set, e.g., the first instance
instance_idx = 0
sample_instance = X_test.iloc[instance_idx]

print(f"\n--- Waterfall Plot for Sample Instance (Index: {instance_idx}) ---")
print("Actual Win Percentage:", y_test.iloc[instance_idx])
print("Predicted Win Percentage:", best_rf.predict(sample_instance.to_frame().T)[0])

# Create a SHAP Explanation object for the waterfall plot
shap_explanation = shap.Explanation(values=shap_values_obj[instance_idx],
                                   base_values=explainer.expected_value,
                                   data=sample_instance,
                                   feature_names=X_test.columns.tolist())

plt.figure(figsize=(10, 6)) # Explicitly create a figure for the waterfall plot
shap.plots.waterfall(shap_explanation, show=False)
plt.title(f'SHAP Waterfall Plot for Instance {instance_idx}')
plt.tight_layout()
plt.show()
plt.close() # Close the figure